import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import ClientProviders from "@/components/shared/header/client-providers";

export const metadata: Metadata = {
  title: "Create App",
  description: "Generated by create app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Header />
      {/* <body>{children}</body> */}
      <ClientProviders>{children}</ClientProviders>
      <Footer />
    </html>
  );
}
